name: 'Setup UV'
description: 'Install and cache UV dependencies for HelpCenter Backend'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Set up Python
      shell: bash
      run: uv python install 3.11

    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION || '3.11' }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ env.PYTHON_VERSION || '3.11' }}-

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
      continue-on-error: false
