"""init full schema

Revision ID: a9ae45e04cf3
Revises:
Create Date: 2025-09-22 04:51:51.808605

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9ae45e04cf3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("category"):
        op.create_table(
            "category",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
        op.create_index(op.f("ix_category_slug"), "category", ["slug"], unique=True)

    if not _table_exists("feedback"):
        op.create_table(
            "feedback",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("expect_reply", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    if not _table_exists("media"):
        op.create_table(
            "media",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("alt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if not _table_exists("userguide"):
        op.create_table(
            "userguide",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("body", postgresql.JSON(astext_type=sa.Text()), nullable=False),
            sa.Column("estimated_read_time", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_userguide_slug"), "userguide", ["slug"], unique=True)

    if not _table_exists("guidecategorylink"):
        op.create_table(
            "guidecategorylink",
            sa.Column("guide_id", sa.Uuid(), nullable=False),
            sa.Column("category_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(
                ["category_id"],
                ["category.id"],
            ),
            sa.ForeignKeyConstraint(
                ["guide_id"],
                ["userguide.id"],
            ),
            sa.PrimaryKeyConstraint("guide_id", "category_id"),
        )

    if not _table_exists("guidemedialink"):
        op.create_table(
            "guidemedialink",
            sa.Column("guide_id", sa.Uuid(), nullable=False),
            sa.Column("media_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(
                ["guide_id"],
                ["userguide.id"],
            ),
            sa.ForeignKeyConstraint(
                ["media_id"],
                ["media.id"],
            ),
            sa.PrimaryKeyConstraint("guide_id", "media_id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guidemedialink")
    op.drop_table("guidecategorylink")
    op.drop_index(op.f("ix_userguide_slug"), table_name="userguide")
    op.drop_table("userguide")
    op.drop_table("media")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_category_slug"), table_name="category")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
