steps:
  # Unit test (common)
  - name: test-common
    image: python:3.11-slim
    volumes:
      - name: uv-cache
        path: /root/.cache/uv
      - name: venv-cache
        path: /app/.venv
    commands:
      - |
        set -e
        pip install uv
        uv python install 3.11
        uv sync --frozen
        uv run flake8 common/ --max-line-length=100 --ignore=E203,W503,F821,E402
        uv run black --check common/ --line-length=100
        uv run isort --check-only common/ --profile black
        uv run pytest tests/unit/ -v --cov=common --cov-report=xml
    when:
      event: [push, pull_request]
      paths:
        - common/**
        - graphql_api/**
        - editor_api/**
        - tests/**
        - .woodpecker/**
        - .forgejo/**

  # Integration test (GraphQL)
  - name: test-graphql
    image: python:3.11-slim
    depends_on:
      - test-common
    services:
      postgres:
        image: postgres:16
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
      redis:
        image: redis:7-alpine
    volumes:
      - name: uv-cache
        path: /root/.cache/uv
      - name: venv-cache
        path: /app/.venv
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      REDIS_URL: redis://redis:6379
      TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@postgres:5432/test_db
      ENVIRONMENT: test
      SECRET_KEY: test-secret-key
      DEV_EDITOR_KEY: test-editor-key
      GCS_BUCKET_NAME: test-bucket
      ALLOWED_ORIGINS: http://localhost:3000
    commands:
      - |
        set -e
        pip install uv
        uv python install 3.11
        uv sync --frozen
        uv run flake8 graphql_api/ --max-line-length=100 --ignore=E203,W503,F821,E402
        uv run black --check graphql_api/ --line-length=100
        uv run isort --check-only graphql_api/ --profile black
        uv run python -m alembic upgrade head
        uv run pytest tests/integration/graphql_api/ -v --cov=graphql_api --cov-report=xml
    when:
      event: [push, pull_request]
      paths:
        - graphql_api/**
        - common/**
        - tests/integration/graphql_api/**
        - .woodpecker/**
        - .forgejo/**

  # Integration test (Editor)
  - name: test-editor
    image: python:3.11-slim
    depends_on:
      - test-common
    services:
      postgres:
        image: postgres:16
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
      redis:
        image: redis:7-alpine
    volumes:
      - name: uv-cache
        path: /root/.cache/uv
      - name: venv-cache
        path: /app/.venv
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      REDIS_URL: redis://redis:6379
      TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@postgres:5432/test_db
      ENVIRONMENT: test
      SECRET_KEY: test-secret-key
      DEV_EDITOR_KEY: test-editor-key
      GCS_BUCKET_NAME: test-bucket
      ALLOWED_ORIGINS: http://localhost:3000
    commands:
      - |
        set -e
        pip install uv
        uv python install 3.11
        uv sync --frozen
        uv run flake8 editor_api/ --max-line-length=100 --ignore=E203,W503,F821,E402
        uv run black --check editor_api/ --line-length=100
        uv run isort --check-only editor_api/ --profile black
        uv run python -m alembic upgrade head
        uv run pytest tests/integration/editor_api/ -v --cov=editor_api --cov-report=xml
    when:
      event: [push, pull_request]
      paths:
        - editor_api/**
        - common/**
        - tests/integration/editor_api/**
        - .woodpecker/**
        - .forgejo/**

  # Full integration test
  - name: test-integration
    image: python:3.11-slim
    depends_on:
      - test-common
      - test-graphql
      - test-editor
    services:
      postgres:
        image: postgres:16
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
      redis:
        image: redis:7-alpine
    volumes:
      - name: uv-cache
        path: /root/.cache/uv
      - name: venv-cache
        path: /app/.venv
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      REDIS_URL: redis://redis:6379
      TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@postgres:5432/test_db
      ENVIRONMENT: test
      SECRET_KEY: test-secret-key
      DEV_EDITOR_KEY: test-editor-key
      GCS_BUCKET_NAME: test-bucket
      ALLOWED_ORIGINS: http://localhost:3000
    commands:
      - |
        set -e
        pip install uv
        uv python install 3.11
        uv sync --frozen
        uv run python -m alembic upgrade head
        uv run pytest tests/integration/ -v
    when:
      event: [push, pull_request]

  # Security scan
  - name: security
    image: python:3.11-slim
    volumes:
      - name: uv-cache
        path: /root/.cache/uv
      - name: venv-cache
        path: /app/.venv
    commands:
      - |
        set -e
        pip install uv bandit
        uv python install 3.11
        uv sync --frozen
        uv run bandit -r common/ graphql_api/ editor_api/ -f json -o bandit-report.json || true
    when:
      event: [push, pull_request]
      paths:
        - common/**
        - graphql_api/**
        - editor_api/**
        - .woodpecker/**
        - .forgejo/**

  # Build and push images
  - name: build-and-push
    image: google/cloud-sdk:latest
    depends_on:
      - test-common
      - test-graphql
      - test-editor
      - test-integration
      - security
    services:
      docker:
        image: docker:dind
        privileged: true
    secrets:
      - GOOGLE_CLOUD_PROJECT
      - HELPCENTER_CICD
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
      PROJECT_ID: ${GOOGLE_CLOUD_PROJECT}
      HELPCENTER_CICD: ${HELPCENTER_CICD}
    commands:
      - |
        set -e
        echo "$${HELPCENTER_CICD}" | base64 -d > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file /tmp/gcp-key.json
        gcloud config set project $${PROJECT_ID}
        gcloud auth configure-docker --quiet

        if [ "$${CI_COMMIT_REF}" = "main" ]; then
          ENV_NAME="production"
        else
          ENV_NAME="staging"
        fi

        # Build and push GraphQL image
        docker build \
          -f Dockerfile.uv \
          -t gcr.io/$${PROJECT_ID}/helpcenter-graphql-api:$${CI_COMMIT_SHA} \
          -t gcr.io/$${PROJECT_ID}/helpcenter-graphql-api:latest \
          --build-arg ENVIRONMENT=$${ENV_NAME} \
          .
        docker push gcr.io/$${PROJECT_ID}/helpcenter-graphql-api:$${CI_COMMIT_SHA}
        docker push gcr.io/$${PROJECT_ID}/helpcenter-graphql-api:latest

        # Build and push Editor image
        docker build \
          -f editor_api/Dockerfile.uv \
          -t gcr.io/$${PROJECT_ID}/helpcenter-editor-api:$${CI_COMMIT_SHA} \
          -t gcr.io/$${PROJECT_ID}/helpcenter-editor-api:latest \
          --build-arg ENVIRONMENT=$${ENV_NAME} \
          .
        docker push gcr.io/$${PROJECT_ID}/helpcenter-editor-api:$${CI_COMMIT_SHA}
        docker push gcr.io/$${PROJECT_ID}/helpcenter-editor-api:latest
    when:
      event: push
      branch: main
      paths:
        - graphql_api/**
        - editor_api/**
        - scripts/**
        - .woodpecker/**
        - .forgejo/**
